title: Oğul Köseoğlu
description: Translator and interpreter based in Turkey, providing services in English and Turkish. I mainly focus on human rights law, journalism, social theory, and literature. Experienced localization linguist. Notary certified legal translator. Bachelor of Letters. Reader. Chess player.

plugins:
- jekyll-remote-theme
remote_theme: broccolini/athena
